// <auto-generated />
using System;
using IndTrace.Persistence.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndTrace.Persistence.Migrations
{
    [DbContext(typeof(IndTraceDbContext))]
    [Migration("20230827231414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndTrace.Domain.Entities.BarCode", b =>
                {
                    b.Property<int>("BarCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BarCodeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BarCodeId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("FlowStatus")
                        .HasColumnType("int")
                        .HasColumnName("FlowStatus");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Label");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("PartStatus")
                        .HasColumnType("int")
                        .HasColumnName("PartStatus");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.HasKey("BarCodeId")
                        .HasName("PK.IndTraceData.BarCodes.BarCodeId");

                    b.HasIndex("BarCodeId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.BarCodes.BarCodeId");

                    b.HasIndex("FlowStatus");

                    b.HasIndex("Label")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.BarCodes.Label");

                    b.HasIndex("MachineId");

                    b.HasIndex("PartStatus");

                    b.HasIndex("ProductId");

                    b.ToTable("BarCodes", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ConfigApp", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppId"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Client");

                    b.Property<string>("ConfigAppId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Factory");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Line");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("Pc")
                        .HasColumnType("int");

                    b.Property<int>("PlcId")
                        .HasColumnType("int")
                        .HasColumnName("PlcId");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Project");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Version");

                    b.HasKey("AppId")
                        .HasName("PK.IndTraceData.ConfigApps.AppId");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.ConfigApps.AppId");

                    b.ToTable("ConfigApps", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ConfigDatabaseLog", b =>
                {
                    b.Property<int>("DatabaseLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DatabaseLogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatabaseLogId"));

                    b.Property<string>("DatabaseUser")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Object")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Tsql")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TSQL");

                    b.Property<string>("XmlEvent")
                        .IsRequired()
                        .HasColumnType("xml");

                    b.HasKey("DatabaseLogId")
                        .HasName("PK_DatabaseLog_DatabaseLogID");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("DatabaseLogId"), false);

                    b.ToTable("Config.DatabaseLog", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ConfigDb", b =>
                {
                    b.Property<string>("DatabaseVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Database Version");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SystemInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SystemInformationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemInformationId"));

                    b.Property<DateTime>("VersionDate")
                        .HasColumnType("datetime2");

                    b.ToTable("ConfigDbs", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ConnectionStatus", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Message");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("MachineId");

                    b.ToTable("StatusConnections", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Cycle", b =>
                {
                    b.Property<int>("CycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CycleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleId"));

                    b.Property<int>("BarCodeId")
                        .HasColumnType("int")
                        .HasColumnName("BarCodeId");

                    b.Property<int>("CycleStatus")
                        .HasColumnType("int")
                        .HasColumnName("CycleStatus");

                    b.Property<int>("CycleTime")
                        .HasColumnType("int")
                        .HasColumnName("CycleTime");

                    b.Property<DateTime>("FinishedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("FinishedOn");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<int>("PartStatus")
                        .HasColumnType("int")
                        .HasColumnName("PartStatus");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("StartedOn");

                    b.Property<int>("TaktTime")
                        .HasColumnType("int")
                        .HasColumnName("TaktTime");

                    b.HasKey("CycleId")
                        .HasName("PK.IndTraceData.Cycles.CycleId");

                    b.HasIndex("BarCodeId")
                        .HasDatabaseName("IDX.IndTraceData.Cycles.BarCodeId");

                    b.HasIndex("CycleId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Cycles.CicloId");

                    b.HasIndex("CycleStatus");

                    b.HasIndex("MachineId");

                    b.HasIndex("PartStatus");

                    b.ToTable("Cycles", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Defect", b =>
                {
                    b.Property<int>("DefectId")
                        .HasColumnType("int")
                        .HasColumnName("DefectId");

                    b.Property<int>("DefectTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DefectTypeId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ShortName");

                    b.HasKey("DefectId")
                        .HasName("PK.IndTraceData.Defects.DefectId");

                    b.HasIndex("DefectId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Defects.DefectId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Defects.Name");

                    b.ToTable("Defects", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.DefectRegister", b =>
                {
                    b.Property<int>("DefectRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DefectRegisterId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefectRegisterId"));

                    b.Property<int>("BarCodeId")
                        .HasColumnType("int")
                        .HasColumnName("BarCodeId");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefectId")
                        .HasColumnType("int")
                        .HasColumnName("DefectId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PartsQuantity")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("PartsQuantity");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("TimeStamp");

                    b.HasKey("DefectRegisterId")
                        .HasName("PK.IndTraceData.DefectsRegister.DefectRegisterId");

                    b.HasIndex("BarCodeId");

                    b.HasIndex("DefectId");

                    b.HasIndex("MachineId");

                    b.ToTable("DefectsRegister", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Edge", b =>
                {
                    b.Property<int>("EdgeId")
                        .HasColumnType("int")
                        .HasColumnName("EdgeId");

                    b.Property<int>("FromMachineId")
                        .HasColumnType("int");

                    b.Property<int>("ToMachineId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Weight");

                    b.Property<int?>("WorkFlowId")
                        .HasColumnType("int");

                    b.HasKey("EdgeId")
                        .HasName("PK.IndTraceData.Edges.EdgeId");

                    b.HasIndex("EdgeId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Edges.EdgeId");

                    b.HasIndex("FromMachineId");

                    b.HasIndex("ToMachineId");

                    b.HasIndex("WorkFlowId");

                    b.ToTable("Edges", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.EpDaqHealth", b =>
                {
                    b.Property<int>("RegisterEpDaqHealtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegisterEpDaqHealtId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterEpDaqHealtId"));

                    b.Property<DateTime>("FechaHoraRegistro")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("TimeStamp");

                    b.HasKey("RegisterEpDaqHealtId")
                        .HasName("PK.IndTraceData.EpDaqHealth.RegisterEpDaqHealtId");

                    b.ToTable("EpDaqHealth", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.KpiOee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("Oee")
                        .HasColumnType("decimal(12, 4)")
                        .HasColumnName("OEE");

                    b.Property<decimal>("Performance")
                        .HasColumnType("decimal(12, 4)");

                    b.Property<decimal>("Quality")
                        .HasColumnType("decimal(12, 4)");

                    b.HasKey("Id");

                    b.ToTable("KPI.OEE", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnableAppTraceability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnableAppTraceability")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("EnableBypassTraceability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnableBypassTraceability")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Location");

                    b.Property<int>("MachineType")
                        .HasColumnType("int")
                        .HasColumnName("MachineType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Description");

                    b.Property<int>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleId");

                    b.Property<int?>("WorkFlowId")
                        .HasColumnType("int");

                    b.Property<int>("WorkFlowType")
                        .HasColumnType("int")
                        .HasColumnName("WorkFlowType");

                    b.HasKey("MachineId")
                        .HasName("PK.IndTraceData.Machines.MachineId");

                    b.HasIndex("MachineId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Machines.MachineId");

                    b.HasIndex("MachineType");

                    b.HasIndex("WorkFlowId");

                    b.HasIndex("WorkFlowType");

                    b.ToTable("Machines", null, t =>
                        {
                            t.Property("Description")
                                .HasColumnName("Description1");
                        });
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.MachinePlc", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("PlcId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifiedOn");

                    b.HasKey("MachineId", "PlcId");

                    b.HasIndex("PlcId");

                    b.ToTable("MachinePlcs", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.MachineStatus", b =>
                {
                    b.Property<decimal>("BreakDownTime")
                        .HasColumnType("Decimal(18,4)")
                        .HasColumnName("BreakDownTime");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<int>("StatusMachineId")
                        .HasColumnType("int")
                        .HasColumnName("StatusMachine");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("Datetime2(7)")
                        .HasColumnName("UpdatedOn");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineStatus", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.MasterLabel", b =>
                {
                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<string>("MasterLabelCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("MasterLabelCode");

                    b.Property<int>("MasterLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MasterLabelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasterLabelId"));

                    b.ToTable("MasterLabel", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Order", b =>
                {
                    b.Property<int>("LeaderId")
                        .HasColumnType("int")
                        .HasColumnName("LeaderId");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int")
                        .HasColumnName("OperatorID");

                    b.Property<DateTime>("OrderEnd")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("OrderSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderTime")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("ProgrammerId")
                        .HasColumnType("int")
                        .HasColumnName("ProgrammerID");

                    b.Property<int>("ResultsId")
                        .HasColumnType("int")
                        .HasColumnName("ResultsID");

                    b.Property<int>("TimeStamp")
                        .HasColumnType("int");

                    b.Property<int>("ToolingId")
                        .HasColumnType("int")
                        .HasColumnName("ToolingId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Orders.OrderId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.PerformanceSpec", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.ToTable("PerformanceSpecs", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Plc", b =>
                {
                    b.Property<int>("PlcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlcId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlcId"));

                    b.Property<string>("BrandOwner")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("BrandOwner");

                    b.Property<string>("CommLibrary")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CommLibrary");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("IpAddress");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Options");

                    b.Property<string>("PlcBrand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PlcBrand");

                    b.Property<string>("PlcType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PlcType");

                    b.HasKey("PlcId")
                        .HasName("PK.IndTraceData.Plcs.PlcId");

                    b.HasIndex("PlcId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Plcs.PlcId");

                    b.ToTable("Plcs", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AliasPartNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("AliasPartNumber");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("CustomerPartNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CustomerPartNumber");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IsActive");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PartNumber");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ProductName");

                    b.Property<int>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleId");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("ProductId")
                        .HasName("PK.IndTraceData.Products.ProductId");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Products.ProductId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ProductSpec", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<int>("PerformanceSpecId")
                        .HasColumnType("int")
                        .HasColumnName("PerformanceSpecId");

                    b.Property<string>("PerformanceSpecsName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("PerformanceSpecsName");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int>("ProductSpecId")
                        .HasColumnType("int")
                        .HasColumnName("ProductSpecId");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipeId");

                    b.Property<string>("RecipeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("RecipeType");

                    b.Property<int>("ToolId")
                        .HasColumnType("int")
                        .HasColumnName("ToolId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ToolId");

                    b.ToTable("ProductSpecs", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("PK.IndTraceData.Recipes.Id");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Register", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegisterId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterId"));

                    b.Property<int>("CycleId")
                        .HasColumnType("int")
                        .HasColumnName("CycleId");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("DataType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<int>("StatusValueId")
                        .HasColumnType("int")
                        .HasColumnName("StatusValueId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Value");

                    b.Property<int>("VariableId")
                        .HasColumnType("int")
                        .HasColumnName("VariableID");

                    b.HasKey("RegisterId")
                        .HasName("PK.IndTraceData.Registers.RegisterId");

                    b.HasIndex("CycleId");

                    b.HasIndex("RegisterId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Registers.RegisterId");

                    b.HasIndex("VariableId");

                    b.ToTable("Registers", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Rule", b =>
                {
                    b.Property<int>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleID");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RuleJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("RuleId")
                        .HasName("PK_Rules");

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SettingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nchar(4000)")
                        .HasColumnName("Config")
                        .IsFixedLength();

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.HasKey("SettingId")
                        .HasName("PK.IndTraceData.Settings.SettingId");

                    b.HasIndex("MachineId");

                    b.HasIndex("SettingId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Settings.SettingId");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.StatusConfiguration", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Message");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("Datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasIndex("MachineId");

                    b.ToTable("StatusConfigurations", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Stoppage", b =>
                {
                    b.Property<int>("StoppageId")
                        .HasColumnType("int")
                        .HasColumnName("StoppageId");

                    b.Property<bool?>("ApplyForProduction")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<string>("Description2")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description2");

                    b.Property<int>("ItemProperty")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ShortName");

                    b.Property<string>("StoppageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("StoppageName");

                    b.Property<int>("StoppageTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StoppageTypeId");

                    b.HasKey("StoppageId")
                        .HasName("PK.IndTraceData.Stoppages.StoppageId");

                    b.ToTable("Stoppages", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.StoppageRegister", b =>
                {
                    b.Property<int>("StoppageRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StoppageRegisterId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoppageRegisterId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Comment");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("FinishedOn");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("int")
                        .HasColumnName("ProductionOrderId");

                    b.Property<DateTime>("RegistedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("RegistedOn");

                    b.Property<DateTime>("StartedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("StartedOn")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StoppageId")
                        .HasColumnType("int")
                        .HasColumnName("StoppageId");

                    b.Property<decimal>("StoppedTime")
                        .HasColumnType("decimal(10, 4)")
                        .HasColumnName("StoppedTime");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("TimeStamp");

                    b.HasKey("StoppageRegisterId")
                        .HasName("PK.IndTraceData.StoppagesRegister.StoppageRegisterId");

                    b.HasIndex("MachineId");

                    b.HasIndex("StoppageId");

                    b.ToTable("RegisterStoppages", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Tooling", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ToolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolId"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("ToolId")
                        .HasName("PK.IndTraceData.Tooling.ToolId");

                    b.ToTable("Toolings", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("UserId")
                        .HasName("PK_Users");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Variable", b =>
                {
                    b.Property<int>("VariableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VariableId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariableId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Address");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Alias");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(240)")
                        .HasColumnName("Description");

                    b.Property<int>("Direction")
                        .HasColumnType("int")
                        .HasColumnName("Direction");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("IsActive");

                    b.Property<int>("Length")
                        .HasColumnType("int")
                        .HasColumnName("Length");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.Property<string>("NativeAddress")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("NativeAddress");

                    b.Property<string>("NativeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("NativeType");

                    b.Property<string>("NetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("NetType");

                    b.Property<int>("PlcId")
                        .HasColumnType("int");

                    b.Property<int>("TagStatus")
                        .HasColumnType("int")
                        .HasColumnName("TagStatus");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Value");

                    b.Property<int>("VariableGroupId")
                        .HasColumnType("int")
                        .HasColumnName("VariableGroupId");

                    b.Property<int?>("VariableSpecId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("VariableSpecId");

                    b.HasKey("VariableId")
                        .HasName("PK.IndTraceData.Variables.VariableId");

                    b.HasIndex("VariableGroupId");

                    b.HasIndex("VariableId")
                        .IsUnique()
                        .HasDatabaseName("IDX.IndTraceData.Variables.VariableId");

                    b.ToTable("Variables", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.VariablesGroup", b =>
                {
                    b.Property<int>("VariableGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VariableGroupId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariableGroupId"));

                    b.Property<string>("VariableGroupName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("VariableGroupName");

                    b.HasKey("VariableGroupId")
                        .HasName("PK.IndTraceData.VariablesGroups.VariableGroupId");

                    b.ToTable("VariablesGroups", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.WorkFlow", b =>
                {
                    b.Property<int>("WorkFlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WorkFlowId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkFlowId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("LastMachineId")
                        .HasColumnType("int")
                        .HasColumnName("LastMachineId");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifiedOn");

                    b.Property<int>("NextMachineId")
                        .HasColumnType("int")
                        .HasColumnName("NextMachineId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int>("RuleId")
                        .HasColumnType("int")
                        .HasColumnName("RuleId");

                    b.HasKey("WorkFlowId")
                        .HasName("PK.IndTraceData.WorkFlows.WorkFlowId");

                    b.HasIndex("LastMachineId");

                    b.HasIndex("NextMachineId");

                    b.ToTable("WorkFlows", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.CycleStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("PK.IndTraceData.CycleStatus.Id");

                    b.ToTable("CycleStatus", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.FlowStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("FlowStatus", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.MachineTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("MachineType", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.PartStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("PartStatus", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.ResultValidationEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ResultValidation", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.TagsGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("TagsGroups", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Enum.WorkFlowTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("WorkFlowType", (string)null);
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.BarCode", b =>
                {
                    b.HasOne("IndTrace.Domain.Enum.FlowStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("FlowStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.BarCodes.FlowStatus");

                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.BarCodes.Machines");

                    b.HasOne("IndTrace.Domain.Enum.PartStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("PartStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.BarCodes.PartStatus");

                    b.HasOne("IndTrace.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.BarCodes.Products");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ConnectionStatus", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.StatusConnections.MachineId");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Cycle", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.BarCode", null)
                        .WithMany()
                        .HasForeignKey("BarCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Cycles.BarCodes");

                    b.HasOne("IndTrace.Domain.Enum.CycleStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("CycleStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Cycles.CycleStatus");

                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Cycles.Machines");

                    b.HasOne("IndTrace.Domain.Enum.PartStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("PartStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Cycles.PartStatus");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.DefectRegister", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.BarCode", null)
                        .WithMany()
                        .HasForeignKey("BarCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.DefectsRegister.BarCodeId");

                    b.HasOne("IndTrace.Domain.Entities.Defect", null)
                        .WithMany()
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.DefectsRegister.DefectId");

                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.DefectsRegister.MachineId");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Edge", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", "FromMachine")
                        .WithMany("FromEdges")
                        .HasForeignKey("FromMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndTrace.Domain.Entities.Machine", "ToMachine")
                        .WithMany("ToEdges")
                        .HasForeignKey("ToMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IndTrace.Domain.Entities.WorkFlow", null)
                        .WithMany("Edges")
                        .HasForeignKey("WorkFlowId");

                    b.Navigation("FromMachine");

                    b.Navigation("ToMachine");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Machine", b =>
                {
                    b.HasOne("IndTrace.Domain.Enum.MachineTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("MachineType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Machines.MachineType");

                    b.HasOne("IndTrace.Domain.Entities.WorkFlow", null)
                        .WithMany("Machine")
                        .HasForeignKey("WorkFlowId");

                    b.HasOne("IndTrace.Domain.Enum.WorkFlowTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkFlowType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Machines.WorkFlowType");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.MachinePlc", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndTrace.Domain.Entities.Plc", null)
                        .WithMany()
                        .HasForeignKey("PlcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.MachineStatus", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.MachineStatus.MachineId");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.ProductSpec", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.ProductSpecs.MachineId");

                    b.HasOne("IndTrace.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.ProductSpecs.ProductId");

                    b.HasOne("IndTrace.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.ProductSpecs.RecipeId");

                    b.HasOne("IndTrace.Domain.Entities.Tooling", "Tooling")
                        .WithMany()
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.ProductSpecs.ToolId");

                    b.Navigation("Machine");

                    b.Navigation("Product");

                    b.Navigation("Recipe");

                    b.Navigation("Tooling");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Register", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Cycle", null)
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Registers.Cycles");

                    b.HasOne("IndTrace.Domain.Entities.Variable", null)
                        .WithMany()
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Registers.Variables");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Setting", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Settings.Machines");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.StatusConfiguration", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.StatusConfigurations.MachineId");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.StoppageRegister", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.RegisterStoppages.MachineId");

                    b.HasOne("IndTrace.Domain.Entities.Stoppage", null)
                        .WithMany()
                        .HasForeignKey("StoppageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.RegisterStoppages.StoppageId");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Variable", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.VariablesGroup", "VariablesGroups")
                        .WithMany()
                        .HasForeignKey("VariableGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.Variables.VariableGroupId");

                    b.Navigation("VariablesGroups");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.WorkFlow", b =>
                {
                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("LastMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.WorkFlows.Machines.LastMachineId");

                    b.HasOne("IndTrace.Domain.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("NextMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK.IndTraceData.WorkFlows.Machines.NextMachineId");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.Machine", b =>
                {
                    b.Navigation("FromEdges");

                    b.Navigation("ToEdges");
                });

            modelBuilder.Entity("IndTrace.Domain.Entities.WorkFlow", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Machine");
                });
#pragma warning restore 612, 618
        }
    }
}
