// <copyright file="VariablesRawData.cs" company="Exxerpro Solutions SA de CV">
// Copyright (c) Exxerpro Solutions SA de CV. Licensed under the GNU Affero General Public License v3.0 or later.
// </copyright>
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using IndTrace.Domain.Entities;

namespace IndTrace.TestData.RawData;

/// <summary>
/// Static test data for Variable entities.
/// OPTIMIZED: Contains only entities used in failing tests (24 instead of 19K+).
/// Generated by convert_variables_optimized.py on 31/08/2025 13:44:46
/// Based on entity discovery from Application.AggregationTests
/// </summary>
internal static class VariablesRawData
{
    private static readonly ImmutableDictionary<int, Variable> _variablesDict =
        new Dictionary<int, Variable>
        {
            [1] = new Variable
            {
                VariableId = 1,
                MachineId = 100,
                PlcId = 100,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [2] = new Variable
            {
                VariableId = 2,
                MachineId = 100,
                PlcId = 100,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [3] = new Variable
            {
                VariableId = 3,
                MachineId = 100,
                PlcId = 100,
                Name = "ValorInt1",
                Description = "ValorInt1",
                Alias = "DB257.W12",
                Address = "DB257.W12",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 0,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [4] = new Variable
            {
                VariableId = 4,
                MachineId = 100,
                PlcId = 100,
                Name = "ValorInt2",
                Description = "ValorInt2",
                Alias = "DB257.W14",
                Address = "DB257.W14",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 0,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [11] = new Variable
            {
                VariableId = 11,
                MachineId = 100,
                PlcId = 100,
                Name = "ValorReal6",
                Description = "ValorReal6",
                Alias = "DB257.D80",
                Address = "DB257.D80",
                NetType = "System.Single",
                Length = 1,
                IsActive = 0,
                Direction = 1,
                VariableGroupId = 2,
                Validated = true
            },
            [43] = new Variable
            {
                VariableId = 43,
                MachineId = 400,
                PlcId = 400,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [44] = new Variable
            {
                VariableId = 44,
                MachineId = 400,
                PlcId = 400,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [82] = new Variable
            {
                VariableId = 82,
                MachineId = 500,
                PlcId = 500,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [83] = new Variable
            {
                VariableId = 83,
                MachineId = 500,
                PlcId = 500,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [100] = new Variable
            {
                VariableId = 100,
                MachineId = 500,
                PlcId = 500,
                Name = "Test Current HOUSING",
                Description = "Test Current HOUSING",
                Alias = "DB257.X10.3",
                Address = "DB257.X10.3",
                NetType = "System.Boolean",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [209] = new Variable
            {
                VariableId = 209,
                MachineId = 200,
                PlcId = 200,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [210] = new Variable
            {
                VariableId = 210,
                MachineId = 200,
                PlcId = 200,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [326] = new Variable
            {
                VariableId = 326,
                MachineId = 400,
                PlcId = 400,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [327] = new Variable
            {
                VariableId = 327,
                MachineId = 400,
                PlcId = 400,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [443] = new Variable
            {
                VariableId = 443,
                MachineId = 600,
                PlcId = 600,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [444] = new Variable
            {
                VariableId = 444,
                MachineId = 600,
                PlcId = 600,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [560] = new Variable
            {
                VariableId = 560,
                MachineId = 700,
                PlcId = 700,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [561] = new Variable
            {
                VariableId = 561,
                MachineId = 700,
                PlcId = 700,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [677] = new Variable
            {
                VariableId = 677,
                MachineId = 800,
                PlcId = 800,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [678] = new Variable
            {
                VariableId = 678,
                MachineId = 800,
                PlcId = 800,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [794] = new Variable
            {
                VariableId = 794,
                MachineId = 900,
                PlcId = 900,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [795] = new Variable
            {
                VariableId = 795,
                MachineId = 900,
                PlcId = 900,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [911] = new Variable
            {
                VariableId = 911,
                MachineId = 300,
                PlcId = 300,
                Name = "PartStatusPlc",
                Description = "PartStatusPlc",
                Alias = "DB257.W0",
                Address = "DB257.W0",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            },
            [912] = new Variable
            {
                VariableId = 912,
                MachineId = 300,
                PlcId = 300,
                Name = "CycleStatusPlc",
                Description = "CycleStatusPlc",
                Alias = "DB257.W2",
                Address = "DB257.W2",
                NetType = "System.Int16",
                Length = 1,
                IsActive = 1,
                Direction = 1,
                VariableGroupId = 128,
                Validated = true
            }
        }.ToImmutableDictionary();

    /// <summary>
    /// Get all variables as a list (standardized Dict property)
    /// </summary>
    public static IReadOnlyList<Variable> Fixture => _variablesDict.Values.ToList();

    /// <summary>
    /// Get variable by ID with O(1) lookup
    /// </summary>
    public static Variable? GetVariable(int variableId) =>
        _variablesDict.TryGetValue(variableId, out var variable) ? variable : null;

    /// <summary>
    /// Get all variables as immutable dictionary for O(1) operations
    /// </summary>
    public static IImmutableDictionary<int, Variable> Variables => _variablesDict;

    /// <summary>
    /// Check if variable exists by ID
    /// </summary>
    public static bool Contains(int variableId) => _variablesDict.ContainsKey(variableId);

    /// <summary>
    /// Get total count of variables
    /// </summary>
    public static int Count => _variablesDict.Count;

    /// <summary>
    /// Get variables by address pattern (for PLC addressing)
    /// </summary>
    public static IEnumerable<Variable> GetByAddressPattern(string pattern) =>
        _variablesDict.Values.Where(v => v.Address.Contains(pattern));

    /// <summary>
    /// Get variables by NetType (for type-specific operations)
    /// </summary>
    public static IEnumerable<Variable> GetByNetType(string netType) =>
        _variablesDict.Values.Where(v => v.NetType == netType);

    /// <summary>
    /// Get DB block variables (most common addressing scheme)
    /// </summary>
    public static IEnumerable<Variable> GetDbVariables() =>
        _variablesDict.Values.Where(v => v.Address.StartsWith("DB"));

    /// <summary>
    /// Get Temperature and TemperingTime variables (common test scenario)
    /// </summary>
    public static (Variable? Temperature, Variable? TemperingTime) GetTemperatureVariables() =>
        (GetVariable(45), GetVariable(46));
}
